[package]
authors = ["The Rust Project Developers"]
name = "panic_abort"
version = "0.1.0"

[lib]
path = "lib.rs"
test = false
bench = false
doc = false

[dependencies.libc]
version = "0.2"
default-features = false

[dependencies.libc_shim]
path = "../libc_shim"